#!/usr/bin/env python3
"""Generate src/server/webassets.h from web/ files so the exe is truly standalone.

Run from the project root before building (build.bat does this automatically).
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "server", "webassets.h")

FILES = [
    ("index.html", "web/index.html", "text/html; charset=utf-8"),
    ("style.css",  "web/style.css",  "text/css; charset=utf-8"),
    ("app.js",     "web/app.js",     "text/javascript; charset=utf-8"),
    ("fonts/space-grotesk-latin.woff2",     "web/fonts/space-grotesk-latin.woff2",     "font/woff2"),
    ("fonts/space-grotesk-latin-ext.woff2", "web/fonts/space-grotesk-latin-ext.woff2", "font/woff2"),
]

def c_name(vpath: str) -> str:
    return "ok_asset_" + "".join(c if c.isalnum() else "_" for c in vpath)

def main() -> int:
    lines = [
        "// AUTO-GENERATED by tools/embed_web.py — do not edit.",
        "// Embeds the web dashboard into the exe so a single OptimizeKit.exe always works.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstring>",
        "",
        "namespace ok::webassets {",
        "",
        "struct File {",
        "    const char* path;",
        "    const unsigned char* data;",
        "    unsigned len;",
        "    const char* mime;",
        "};",
        "",
    ]
    for vpath, rel, _mime in FILES:
        p = os.path.join(ROOT, rel)
        if not os.path.exists(p):
            print(f"[embed_web] missing {rel}", file=sys.stderr)
            return 1
        data = open(p, "rb").read()
        name = c_name(vpath)
        lines.append(f"static const unsigned char {name}[] = {{")
        for i in range(0, len(data), 20):
            chunk = data[i:i + 20]
            lines.append("    " + ",".join(str(b) for b in chunk) + ",")
        lines.append("};")
        lines.append("")
    lines += [
        "static const File kFiles[] = {",
    ]
    for vpath, _rel, mime in FILES:
        lines.append(f'    {{"{vpath}", {c_name(vpath)}, sizeof({c_name(vpath)}), "{mime}"}},')
    lines += [
        "};",
        "",
        "inline const File* find(const char* path) {",
        "    for (const auto& f : kFiles)",
        "        if (std::strcmp(f.path, path) == 0) return &f;",
        "    return nullptr;",
        "}",
        "",
        "} // namespace ok::webassets",
        "",
    ]
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    total = sum(len(open(os.path.join(ROOT, r), "rb").read()) for _, r, _ in FILES)
    print(f"[embed_web] wrote {os.path.relpath(OUT, ROOT)} ({total} bytes embedded)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
